---
title: "Example Dashboard with NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

```


```{r}
data("ny_noaa")
```

```{r}
noaa=ny_noaa %>%
  mutate(
    day=day(date),
    month=month.abb[month(date)],
    year=year(date),
    prcp=prcp/10,
    tmax=as.numeric(tmax)/10,
    tmin=as.numeric(tmin)/10) %>% 
  filter(month %in% c('Mar','Jun','Sep','Dec')) %>% 
  mutate(month=fct_relevel(month,'Mar','Jun','Sep','Dec'))

 


```

Column {data-width=650}
-----------------------------------------------------------------------

### Tmax distrobution for season starting months

```{r}

noaa %>% 
  plot_ly(x=~month, y=~tmax,color= ~month,type = "box")

   
```

Column {data-width=350}
-----------------------------------------------------------------------

### Average t_max over the years for season starting months

```{r}
noaa %>% 
  group_by(month,year) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE, color = id)) %>% 
  plot_ly( x=~year,y=~mean_tmax, color = ~month, type = "scatter", mode = "line",alpha = 0.5)
```

### Average snow for season starting months

```{r}

  noaa %>% 
  group_by(month) %>% 
  mutate(avg_snow=mean(snow,na.rm = TRUE)) %>% 
  distinct(month,avg_snow) %>% 
  plot_ly(x=~month,y=~avg_snow, color = ~month, type ='bar')
  
  
```

